inherit_from: https://raw.githubusercontent.com/rails/rails/v7.0.4/.rubocop.yml

Performance:
  Exclude:
    - 'test/**/*'

Style/FrozenStringLiteralComment:
  Enabled: false

Lint/UselessAssignment:
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes
  Include:
    - 'app/**/*'
    - 'test/**/*'
